/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MonkeyLeagueOptimismMintableERC20Abi } from "./MonkeyLeagueOptimismMintableERC20Abi";
export * as factories from "./factories";
export { MonkeyLeagueOptimismMintableERC20Abi__factory } from "./factories/MonkeyLeagueOptimismMintableERC20Abi__factory";
