[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 9999999
auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
foo = { key = "<ETHERSCAN_API_KEY>", chain = 8453, url = "https://api.basescan.org/api/" }