/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface HelloBaseScoreGoalAbiInterface extends utils.Interface {
  functions: {
    "hasScoredGoal(address)": FunctionFragment;
    "scoreGoal()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "hasScoredGoal" | "scoreGoal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasScoredGoal",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "scoreGoal", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "hasScoredGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scoreGoal", data: BytesLike): Result;

  events: {
    "ScoredGoal(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ScoredGoal"): EventFragment;
}

export interface ScoredGoalEventObject {
  scorer: string;
}
export type ScoredGoalEvent = TypedEvent<[string], ScoredGoalEventObject>;

export type ScoredGoalEventFilter = TypedEventFilter<ScoredGoalEvent>;

export interface HelloBaseScoreGoalAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HelloBaseScoreGoalAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    hasScoredGoal(
      scorer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    scoreGoal(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  hasScoredGoal(scorer: string, overrides?: CallOverrides): Promise<boolean>;

  scoreGoal(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    hasScoredGoal(scorer: string, overrides?: CallOverrides): Promise<boolean>;

    scoreGoal(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ScoredGoal(address)"(scorer?: string | null): ScoredGoalEventFilter;
    ScoredGoal(scorer?: string | null): ScoredGoalEventFilter;
  };

  estimateGas: {
    hasScoredGoal(
      scorer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    scoreGoal(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    hasScoredGoal(
      scorer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    scoreGoal(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
