/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloBaseScoreGoalAbi } from "./HelloBaseScoreGoalAbi";
export * as factories from "./factories";
export { HelloBaseScoreGoalAbi__factory } from "./factories/HelloBaseScoreGoalAbi__factory";
