/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MBSOptimismMintableERC20Abi } from "./MBSOptimismMintableERC20Abi";
export * as factories from "./factories";
export { MBSOptimismMintableERC20Abi__factory } from "./factories/MBSOptimismMintableERC20Abi__factory";
