/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MBSTokenOptimismMintableERC20Abi } from "./MBSTokenOptimismMintableERC20Abi";
export * as factories from "./factories";
export { MBSTokenOptimismMintableERC20Abi__factory } from "./factories/MBSTokenOptimismMintableERC20Abi__factory";
