/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MonkeyLeagueOptimismMintableERC20Abi__factory } from "./MonkeyLeagueOptimismMintableERC20Abi__factory";
