/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KaChingCashRegisterV1Abi } from "./KaChingCashRegisterV1Abi";
export * as factories from "./factories";
export { KaChingCashRegisterV1Abi__factory } from "./factories/KaChingCashRegisterV1Abi__factory";
